In [5]:
import numpy as np
import pandas as pd

url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

names=['sepal-length','sepal-width','petal-length','petal-width','Class']

dataset=pd.read_csv(url,names=names)
# print(dataset)

x= dataset.iloc[:,:-1].values
# print(x)
y=dataset.iloc[:,4].values
# print(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
scalar.fit(x_train)
x_train=scalar.transform(x_train)
x_test=scalar.transform(x_test)
print(x_train)
print(x_test)
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=12)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(y_pred)

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))


[[ 1.54747832  1.3286494   1.30135661  1.73040935]
 [-1.74753256 -0.08438984 -1.45142123 -1.37689696]
 [ 1.78283624 -0.55540292  1.30135661  0.9198077 ]
 [-0.92377984  1.79966248 -1.107324   -1.10669641]
 [ 2.13587312 -0.55540292  1.64545384  1.05490797]
 [-1.27681672  0.1511167  -1.27937262 -1.37689696]
 [ 0.25300976 -0.55540292  0.49846307 -0.02589422]
 [ 0.48836768 -0.31989638  1.01460892  0.78470743]
 [-1.15913776  0.1511167  -1.33672216 -1.51199724]
 [ 0.60604664 -0.79090947  0.8425603   0.9198077 ]
 [ 0.95908352  0.1511167   1.01460892  1.59530907]
 [-1.51217464  0.85763632 -1.39407169 -1.24179669]
 [ 0.7237256  -0.08438984  0.78521076  1.05490797]
 [-0.92377984  0.85763632 -1.33672216 -1.37689696]
 [-1.0414588   0.85763632 -1.33672216 -1.37689696]
 [-1.0414588  -0.08438984 -1.27937262 -1.37689696]
 [ 2.37123104  1.79966248  1.47340522  1.05490797]
 [-0.10002712 -0.79090947  0.03966676 -0.02589422]
 [-0.57074296  1.56415594 -1.33672216 -1.37689696]
 [-0.21770608 -0.55540292  0.15