In [3]:
import pandas as pd
import numpy as np

datasets=pd.read_csv("50_Startups_lyst7770.csv")
# print(datasets)

X=datasets.iloc[:,:-1].values
Y=datasets.iloc[:,4].values
# #print(X)

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
A=make_column_transformer((OneHotEncoder(categories="auto"),[3]),remainder="passthrough")

X=A.fit_transform(X)
# print(X)
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test= train_test_split(X,Y, test_size=0.20,random_state=0)




from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,Y_train)

y_pred= regressor.predict(X_test)
print(X_test)
print(pd.DataFrame(Y_test,y_pred))
y_pred1=regressor.predict([[1.0,0.0,0.0,200000,10000,30000]])
print(y_pred1)

from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_test,y_pred))

print(regressor.score(X_test,Y_test))








[[0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]
                       0
103015.201598  103282.38
132582.277608  144259.40
132447.738452  146121.95
71976.098513    77798.83
178537.482211  191050.39
116161.242302  105008.31
67851.692097    81229.06
98791.733747    97483.56
113969.435330  110352.25
167921.065696  166187.94
[198674.75291554]
83502864.03259295
0.9347068473282303
